blog/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>/delete/', views.DeletePostView.as_view(),
         name='delete_post'),
    path('add_post', views.AddPostView.as_view(), name='add_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
    path('like/<slug:slug>', views.PostLike.as_view(), name='post_like'),
    path('category/<category>', views.CatListView.as_view(), name='cats'),
    path('contact', views.contact, name='contact'),
    path('about', views.about, name='about'),
    path('<slug:slug>/edit/', views.EditPostView.as_view(), name='edit_post'),
    ]

move/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('summernote/', include('django_summernote.urls')),
    path('', include('blog.urls'), name='blog_urls'),
    path('accounts/', include('allauth.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from cloudinary.models import CloudinaryField
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


STATUS = ((0, "Draft"), (1, "Published"))


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )
    category = models.ForeignKey(Category, on_delete=models.PROTECT, default=1)
    featured_image = CloudinaryField('image', default='placeholder')
    excerpt = models.TextField(blank=True)
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)
    likes = models.ManyToManyField(
        User, related_name='blogpost_like', blank=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return self.title

    def number_of_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('post_detail', args=(str(self.slug),))


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE,
                             related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    approved = models.BooleanField(default=False)

    class Meta:
        ordering = ["created_on"]

    def __str__(self):
        return f"Comment {self.body} by {self.name}"


class Contact(models.Model):
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()

    def __str__(self):
        return self.email

blog/forms.py
from .models import Comment, Post, Contact
from django import forms


class CommentForm(forms.ModelForm):

    class Meta:

        model = Comment
        fields = ('body', )


class ContactForm(forms.Form):

    first_name = forms.CharField(max_length=50)
    last_name = forms.CharField(max_length=50)
    email_address = forms.EmailField(max_length=150)
    message = forms.CharField(widget=forms.Textarea, max_length=2000)


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('__all__')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'excerpt': forms.Textarea(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }


class EditForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('__all__')

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'slug': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.Select(attrs={'class': 'form-control'}),
            'excerpt': forms.Textarea(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
            }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

blog/views.py
from django.shortcuts import render, get_object_or_404, reverse, redirect
from django.views import generic, View
from django.http import HttpResponseRedirect, HttpResponse
from .models import Post, Comment, Category
from .forms import CommentForm, PostForm, EditForm, ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.contrib import messages
from django.urls import reverse_lazy


class PostList(generic.ListView):

    model = Post
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'index.html'
    paginate_by = 6


class PostDetail(View):

    def get(
        self,
        request,
        slug,
        *args,
        **kwargs
         ):

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = \
            post.comments.filter(approved=True).order_by('-created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        return render(request, 'post_detail.html', {
            'post': post,
            'comments': comments,
            'commented': False,
            'liked': liked,
            'comment_form': CommentForm(),
            })

    def post(
        self,
        request,
        slug,
        *args,
        **kwargs
          ):

        queryset = Post.objects.filter(status=1)
        post = get_object_or_404(queryset, slug=slug)
        comments = \
            post.comments.filter(approved=True).order_by('-created_on')
        liked = False
        if post.likes.filter(id=self.request.user.id).exists():
            liked = True

        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            comment_form.instance.email = request.user.email
            comment_form.instance.name = request.user.username
            comment = comment_form.save(commit=False)
            comment.post = post
            comment.save()
        else:
            comment_form = CommentForm()

        return render(request, 'post_detail.html', {
            'post': post,
            'comments': comments,
            'commented': True,
            'comment_form': comment_form,
            'liked': liked,
            })


class PostLike(View):

    def post(
        self,
        request,
        slug,
        *args,
        **kwargs
         ):
        post = get_object_or_404(Post, slug=slug)

        if post.likes.filter(id=request.user.id).exists():
            post.likes.remove(request.user)
        else:
            post.likes.add(request.user)

        return HttpResponseRedirect(reverse('post_detail', args=[slug]))


class CatListView(generic.ListView):

    template_name = 'category.html'
    context_object_name = 'catlist'

    def get_queryset(self):
        content = {'cat': self.kwargs['category'],
                   'posts': Post.objects.filter(category__name=self.kwargs
                                                ['category']).filter(status=1)}
        return content


def category_list(request):
    category_list = Category.objects.exclude(name='default')
    context = {'category_list': category_list}
    return context


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            return render(request, 'success.html')
    form = ContactForm()
    context = {'form': form}
    return render(request, 'contact.html', context)


def about(request):
    return render(request, 'about.html')


class AddPostView(generic.CreateView):

    model = Post
    form_class = PostForm
    template_name = 'add_blog_post.html'


class EditPostView(generic.UpdateView):

    model = Post
    form_class = EditForm
    template_name = 'edit_post.html'


class DeletePostView(generic.DeleteView):
    model = Post
    template_name = 'delete_post.html'
    success_url = reverse_lazy('home')

templates/about.html
{% extends 'base.html' %} {% block content %}

<style>
    p {
    font-family: Lato, sans-serif;
    }
 </style>
 <div class="masthead">
    <div class="container">
       <div class="row g-0">
          <div class="col-md-6 masthead-text">
             <!-- Post title goes in these h1 tags -->
             <h1 class="post-title">
                <br>
                Nothing happens until something moves!
             </h1>
          </div>
          <div class="d-none d-md-block col-md-6 masthead-image">
             <!-- The featured image URL goes in the src attribute -->
             <img src="https://res.cloudinary.com/deokcf057/image/upload/v1676498555/mmc_logo_cnuudp.jpg" width="100%">
          </div>
       </div>
    </div>
 </div>
 <div class="container">
    <div class="row">
       <div class="col card mb-4  mt-3 left  top">
          <div class="card-body">
             <!-- The post content goes inside the card-text. -->
             <!-- Use the | safe filter inside the template tags -->
             <p class="card-text ">
                Move Mo Chara Blog was created to help be a hub for my passion project, Move Mo Chara Podcast. 
                <br>
                <br>
                Move Mo Chara came about because I am passionate about movement in all forms and I have a natuaral curiosity about what drives people who's careers are built on movement. 
                The podcast is more focused on the movement of body, however, I love movement in all shapes and forms. From moving abroad, careers and travel and most of all, 
                challenging myself to move out of my comfort zone. 
                <br>
                <br>
                I wanted to create a hub where I can expand Mo Move Chara
                beyond the podcast and explore movement in all avenues of life.
                <br>
                <br>
                Albert Einstein said it the best - Nothing happens until something moves!
                <br>
                <br>
                <img src="https://res.cloudinary.com/deokcf057/image/upload/v1676556204/bbj_carly_slgaba.jpg" width="100%" >
             </p>
             <div class="row">
             </div>
          </div>
       </div>
    </div>
    <div class="row">
       <div class="col">
       </div>
    </div>
    <a href="{% url 'home' %}" class="btn btn-dark">Back</a>
 </div>

{% endblock content %}

templates/add_blog_post.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">
                    <br>
                    Add Post</h1>
                <!-- Post author goes before the | the post's created date goes after -->
            </div>
        </div>
              
        </div>
    </div>
    <div>
        <div class="container">
            <br>
            
            <div class="row">
                <div class="col-md-4 card mb-4  mt-3 left  top">
                    <div class="card-body">
                        <div class="form-group">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button class="btn btn-dark">Post</button>
                            </form>
                        </div>
                        <div class="row"></div>
                        <br><br>
                    </div>
                </div>
            </div>
            <a href="{% url 'home' %}"class="btn btn-dark">Back</a>
          </div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html class="h-100" lang="en">
  <head>
    <title>Move Mo Chara Blog</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Blog which developed from a podcast">
    <meta name="keywords" content="Movement, Podcast, Travel">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
    <style>
      body {
        font-family: "Roberto", lato;
        font-size: 17px;
        background-color: #fdfdfd;
      }

      .shadow {
        box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
      }

      .masthead {
        background: #70c6ad;
        height: auto;
        padding-bottom: 15px;
        box-shadow: 0 16px 48px #E3E7EB;
        padding-top: 10px;
      }

      footer {
        padding-top: 15px;
        bottom: 0;
        width: 100%;
        height: 60px;
        /* Set the fixed height of the footer here */
        line-height: 60px;
      }

      .btn {
        margin: 10px;
      }
    </style>
  </head>
  <body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light shadow" id="mainNav">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}"></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown"> 
                {% if request.user.is_authenticated %} 
                {% if request.user.is_superuser %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Admin</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'add_post' %}"> Add Post </a>
                
              </div>
            </li> {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
                <div class="dropdown-menu">
                  <a class="dropdown-item" href="{% url 'account_logout' %}"> Logout </a>
                </div>
              </li>
         </li>
         {% else %} 
         <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Account</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'account_login' %}"> Sign In </a>
                <a class="dropdown-item" href="{% url 'account_signup' %}"> Register </a>
              </div>
            </li> 
            {% endif %} 
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">About</a>
              <div class="dropdown-menu">
                <a class="dropdown-item" href="{% url 'about' %}"> About Me </a>
                <a class="dropdown-item" href="{% url 'contact' %}"> Contact Me </a>
                <a class="dropdown-item" href="https://open.spotify.com/show/3vz3lMbS63UUXyUPaM54b2" target="_blank"> Podcast </a>
              </div>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Categories</a>
              <div class="dropdown-menu"> {% for category in category_list %} <a class="dropdown-item" href="/category/{{ category.name }}">
                  {{ category.name|title }}
                </a> {% endfor %} </div>
            </li>
          </ul>
          <span class="navbar-text text-muted">
            <span class="brand">Move Mo Chara Blog </span>
          </span>
        </div>
      </div>
    </nav>
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2"> {% for message in messages %} <div class="alert {{ message.tags }} alert-dismissible fade show" id="msg" role="alert">
            {{ message | safe }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
          </div> {% endfor %} </div>
      </div>
    </div> {% block content %}
    <!-- Content Goes here --> {% endblock content %}
    <!-- Footer -->
    <footer class="footer masthead mt-auto py-3">
      <div class="container">
        <div class="text-center text-light">
          <h2>Move Mo Chara</h2>
          <p> Nothing Happens Until Something Moves</p>
          <div class="social">
            <h4>Social</h4>
            <!-- Facebook -->
            <div class="bg.light">
              <a href="https://open.spotify.com/show/3vz3lMbS63UUXyUPaM54b2" target="_blank" rel="noopener" aria-label="Visit our Facebook page (opens in a new tab)">
                <i class="fab fa-spotify"></i>
              </a>
              <a href="https://www.instagram.com/movemochara/" target="_blank" rel="noopener" aria-label="Visit our Instagram page (opens in a new tab)">
                <i class="fab fa-instagram"></i>
              </a>
            </div>
          </div>
        </div>
      </div>
    </footer>
    <!-- Javascript for alert system. Messages will disapear after a few seconds -->
    <script>
      setTimeout(function() {
        let messages = document.getElementById("msg")
        let alert = new bootstrap.Alert(messages);
        alert.close();
      }, 2500);
    </script>
  </body>
</html>

templates/category.html
{% extends "base.html" %}


{% block content %}
<style>
    body {
        font-family: "Lucida Console", monospace;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text {
        color: white;
    }

    .card {
        box-shadow: 0 16px 48px #E3E7EB;
    }
</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white">{{ catlist.cat|title }} Blogs</h3>
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>
<div class="container">
    <div class="row">
        
        <!-- Blog Entries Column -->
        <div class="col-md-12 float-left">
            <div class="row">
                {% for post in catlist.posts %}
                <div class="col-md-4">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="image-container">
                            {% if "placeholder" in post.featured_image.url %}
                            <img class="card-img-top"
                                src="https://codeinstitute.s3.amazonaws.com/fullstack/blog/default.jpg">
                            {% else %}
                            <img class="card-img-top" src=" {{ post.featured_image.url }}">
                            {% endif %}
                            <div class="image-flash">
                                <p class="author">Author: {{ post.author }}</p>
                            </div>
                        </div>
                        <h2 class="card-title"> {{ post.title }}</h2>
                        <p class="card-text text-muted h6"> {{ post.author }} | {{ post.created_on}} </p>
                        <p class="card-text">{{ post.excerpt }}</p>
                        <a href="{% url 'post_detail' post.slug  %}" class="btn btn-dark">Read More &rarr;</a>
                    </div>
                </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
                
            </div>
                <div class="row">
                {% endif %}
                {% endfor %}

            </div>
            
        </div>
        
    </div>
    {% if is_paginated %}
    <!-- Bolier plate code we can use -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <div>
        
    </div>
</div>

{% endblock %}

templates/contact.html
{% extends "base.html" %}


{% block content %}
<!--Contact form-->
<style>
  #id_message {
  width: 100%;
  }
</style>

<div class="masthead">
  <div class="container">
      <div class="row g-0">
          <div class="col-md-6 masthead-text">
              <!-- Post title goes in these h1 tags -->
              <h1 class="post-title">
                  <br>
                  Get in Touch</h1>
                  <br>
              <!-- Post author goes before the | the post's created date goes after -->
          </div>
      </div>
            
      </div>
  </div>

<div class="container">
  <div class="row">
      <div class="col-md-4 card mb-4  mt-3 left  top">
          <div class="card-body">
              <div class="form-group">
                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="btn btn-dark" type="submit" value="Submit">
                </form>
              </div>
              <div class="row"></div>
              <br><br>
          </div>
      </div>
  </div>
  <a href="{% url 'home' %}"class="btn btn-dark">Back</a>
</div>
{% endblock content %}

  

templates/delete_post.html
{% extends 'base.html' %} {% block content %}

{% load crispy_forms_tags %}

<div class="masthead">
    <div class="container">
        <div class="row g-0">
            <div class="col-md-6 masthead-text">
                <!-- Post title goes in these h1 tags -->
                <h1 class="post-title">
                    <br>
                    Delete Post</h1>
                <!-- Post author goes before the | the post's created date goes after -->
            </div>
        </div>
              
        </div>
    </div>
    <div>
        <div class="container">
            <br>
            
            <div class="row">
                <div class="col-md-4 card mb-4  mt-3 left  top">
                    <div class="card-body">
                        <div class="form-group">
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                {{ form.as_p }}
                                <button class="btn btn-danger">Delete</button>
                            </form>
                        </div>
                        <div class="row"></div>
                        <br><br>
                    </div>
                </div>
            </div>
            <a href="{% url 'home' %}"class="btn btn-dark">Back</a>
          </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}


{% block content %}
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

<div class="container">
    <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img height="300" class="d-block w-100" src="https://res.cloudinary.com/deokcf057/image/upload/v1676500029/background_hslkey.jpg" alt="First slide">
                    <div class="carousel-caption .d-block">
                        <h4>Welcome Move Mo Chara Blog</h4>
                        <br>
                        <p>Find out what movement means to me! </p>
                        <a href="{% url 'about' %}" class="btn btn-dark">About Me</a>
                    </div>
                </div>
                <div class="carousel-item">
                    <img height="300" class="d-block w-100" src="https://res.cloudinary.com/deokcf057/image/upload/v1676500029/background_hslkey.jpg" alt="Second slide">
                    <div class="carousel-caption .d-block">
                        <h4>Have a story to share or want to find out more?</h4>
                        <br>
                        <a href="{% url 'contact' %}" class="btn btn-dark">Contact Me</a>
                    </div>
                </div>
                <div class="carousel-item">
                    <img height="300" class="d-block w-100" src="https://res.cloudinary.com/deokcf057/image/upload/v1676500029/background_hslkey.jpg" alt="Third slide">
                    <div class="carousel-caption .d-block">
                        <h4>Check out the Move Mo Chara Podcast on spotify! </h4>
                        <br>
                        <a class="btn btn-dark" href="https://open.spotify.com/show/3vz3lMbS63UUXyUPaM54b2?si=36a9d00607d74f6d" target="_blank" >Podcast</a>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
            </a>
        </div>
        <!-- Blog Entries Column -->
        <div class="col-md-12 float-left">
            <div class="row">
                {% for post in post_list %}
                <div class="col-md-4">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="image-container">
                                {% if "placeholder" in post.featured_image.url %}
                                <img class="card-img-top"
                                    src="https://res.cloudinary.com/deokcf057/image/upload/v1676496930/move_mochara_-_Copy_t61wj5.jpg">
                                {% else %}
                                <img alt="Move Mo Chara blog post image of the subject" class="card-img-top" src=" {{ post.featured_image.url }}">
                                {% endif %}
                                <div class="image-flash">
                                    <p class="author">Author: {{ post.author }}</p>
                                </div>
                            </div>
                            <h2 class="card-title"> {{ post.title }}</h2>
                            <p class="card-text text-muted h6"> {{ post.author }} | {{ post.created_on}} </p>
                            <p class="card-text">{{ post.excerpt }}</p>
                            <div class="text-secondary">{{ post.number_of_likes }} <i class="fas fa-heart"></i></div>
                            {% if request.user.is_superuser %}
                                <a href="{% url 'edit_post' post.slug  %}" class="btn btn-light">Edit Post</a>
                                {% endif %}
                            <a href="{% url 'post_detail' post.slug  %}" class="btn btn-dark">Read More &rarr;</a>

                        </div>
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}
            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    {% if is_paginated %}
    <!-- Bolier plate code we can use -->
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li class="bg.dark"><a href="?page={{ page_obj.previous_page_number }}" class="btn btn-secondary">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="btn btn-secondary"> NEXT &raquo;</a></li>
            {% endif %}
        </ul>
    </nav>
    {% endif %}
    <div>
    </div>
</div>
{% endblock %}
 <!--to make the carousel work -->